modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/tool-upgrades/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ToolUpgrades.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tool-upgrades"
itemIcon="toolupgrades:modifier_glowstone"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''With this mod can you upgrade your tools and weapons with modifiers!'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

